# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: not://files v3.0
author: notcalle
description: > # this means to ignore newlines until "baseurl:"
  Random development ramblings, maybe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://notfiles.xyz" # the base hostname & protocol for your site
social:
  name: Calle Englund
  email: calle@notfiles.xyz
  links:
    twitter.com: notCalle
    github.com: notCalle
    mastodon.social: notCalle

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/:year/:month/:day/:title/"
  - scope:
      path: "tag"
    values:
      layout: "tag"
  - scope:
      path: "category"
    values:
      layout: "category"

# Build settings
markdown: kramdown
exclude:
  - CNAME
paginate: 5
paginate_path: "/posts/page:num"
gist:
  noscript: false

# Plugins

# Feed settings
feed:
  posts_limit: 100

jekyll-archives:
  enabled:
    - categories
    - month
    - tags
    - year
  layouts:
    category: archive/category
    month: archive/month
    tag: archive/tag
    year: archive/year

# Jekyll Compose
jekyll_compose:
  auto_open: true

script:
  mathjax:
    src: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js
  mermaid:
    init: mermaid.initialize({theme:"dark"})
    src: https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
