%YAML 1.1
---
name: Deploy not://files v3.0

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Setup git configuration
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Prepare worktree
        run: |
          git fetch --no-tags origin gh-pages
          git worktree add _site gh-pages
          git -C _site merge --no-edit --no-ff --log --strategy=ours \
            ${GITHUB_REF:-$GITHUB_SHA}

      - name: Build site
        run: |
          echo ::group::Jekyll Build
          bundle exec jekyll build
          echo Skip Jekyll > _site/.nojekyll
          cp CNAME _site
          echo ::endgroup::
          echo ::group::Commit Changes
          git -C _site add --all --verbose
          echo changes=$(git -C _site status --short | grep -cv feed.xml) >> $GITHUB_ENV
          git -C _site commit -m 'jekyll build'
          echo ::endgroup::

      # Only redeploy from `main`, and only if something changed, other than
      # timestamp churn in feeds.
      - name: Deploy to pages
        if: ${{ github.ref == 'refs/heads/main' && env.changes > 0}}
        run: |
          git -C _site push

      - name: Cleanup worktree
        run: |
          git worktree remove _site
...
